markdown: rdiscount
safe: false
pygments: true
excerpt_separator: "\n\n\n"

title: DEV:P~!
description: 野生党的领地

author :
  name : perichr
  email : i@perichr.org
  github : perichr
  
url :
  production : http://perichr.org
  github: https://github.com/perichr/perichr.github.io

path:
  blog : /blog.html
  archive : /archive.html
  categories : /categories.html
  tags : /tags.html
  atom : /atom.xml
  rss : /rss.xml
  sitemap : /sitemap.xml
  about : /about.html
  jsonp : /jsonp.js

config:
  disqus : perichr